/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "sanctum.csrf-cookie": [],
    "log-viewer.hosts": [],
    "log-viewer.folders": [],
    "log-viewer.folders.request-download": [
        {
            "name": "folderIdentifier",
            "required": true
        }
    ],
    "log-viewer.folders.clear-cache": [
        {
            "name": "folderIdentifier",
            "required": true
        }
    ],
    "log-viewer.folders.delete": [
        {
            "name": "folderIdentifier",
            "required": true
        }
    ],
    "log-viewer.files": [],
    "log-viewer.files.request-download": [
        {
            "name": "fileIdentifier",
            "required": true
        }
    ],
    "log-viewer.files.clear-cache": [
        {
            "name": "fileIdentifier",
            "required": true
        }
    ],
    "log-viewer.files.delete": [
        {
            "name": "fileIdentifier",
            "required": true
        }
    ],
    "log-viewer.files.clear-cache-all": [],
    "log-viewer.files.delete-multiple-files": [],
    "log-viewer.logs": [],
    "log-viewer.folders.download": [
        {
            "name": "folderIdentifier",
            "required": true
        }
    ],
    "log-viewer.files.download": [
        {
            "name": "fileIdentifier",
            "required": true
        }
    ],
    "log-viewer.index": [
        {
            "name": "view",
            "required": false
        }
    ],
    "telescope": [
        {
            "name": "view",
            "required": false
        }
    ],
    "dashboard": [],
    "profile.edit": [],
    "profile.update": [],
    "profile.destroy": [],
    "register": [],
    "login": [],
    "password.request": [],
    "password.email": [],
    "password.reset": [
        {
            "name": "token",
            "required": true
        }
    ],
    "password.store": [],
    "password.confirm": [],
    "password.update": [],
    "logout": [],
    "incidence.index": [],
    "incidence.show": [
        {
            "name": "incidence",
            "required": true,
            "binding": "id"
        }
    ],
    "incidence.edit": [
        {
            "name": "incidence",
            "required": true,
            "binding": "id"
        }
    ],
    "incidence.update": [
        {
            "name": "incidence",
            "required": true,
            "binding": "id"
        }
    ],
    "incidence.destroy": [
        {
            "name": "incidence",
            "required": true,
            "binding": "id"
        }
    ],
    "incidence.validate": [
        {
            "name": "incidence",
            "required": true,
            "binding": "id"
        }
    ],
    "incidence.close": [
        {
            "name": "incidence",
            "required": true,
            "binding": "id"
        }
    ],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
